[theme]
base = "dark"
primaryColor = "#24C4E5"
backgroundColor = "#0D141C"
secondaryBackgroundColor = "#15232E"
textColor = "#ECF5F8"
font = "sans serif"

[theme.sidebar]
backgroundColor = "#091119"
secondaryBackgroundColor = "#15232E"
textColor = "#ECF5F8"

[server]
address = "127.0.0.1"

[browser]
gatherUsageStats = false
