[theme]
base = "light"
primaryColor = "#137E73"
backgroundColor = "#F6F8FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#172B3A"
font = "sans serif"

[server]
address = "127.0.0.1"

[browser]
gatherUsageStats = false
